site_name: BB/VW Wiki
site_url: https://zhenga8533.github.io/bbvw-wiki/
site_description: A fanmade wiki for the Blaze Black and Volt White ROM hacks.
site_author: Volcaronitee
repo_url: https://github.com/zhenga8533/bbvw-wiki

theme:
  name: material
markdown_extensions:
  - admonition
nav:
  - Home: index.md
  - Action Replay Codes: action_replay_codes.md
  - Important Trainer Rosters: important_trainer_rosters.md
  - Item & Trade Changes: item_&_trade_changes.md
  - Level Up Move Changes: level_up_move_changes.md
  - Pokemon Changes: pokemon_changes.md
  - Trainer Rosters: trainer_rosters.md
  - Wild Pokemon: wild_pokemon.md
