site_name: Blaze Black/Volt White Wiki
site_url: https://zhenga8533.github.io/bbvw-wiki/
site_description: A fanmade wiki for the Blaze Black and Volt White ROM hacks.
site_author: Volcaronitee
repo_url: https://github.com/zhenga8533/bbvw-wiki

theme:
  name: material
  favicon: assets/logo.png
  features:
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
markdown_extensions:
  - admonition
nav:
  - Getting Started:
      - Home: index.md
      - Download Links: getting_started/download_links.md
      - Patching Guide: getting_started/patching_guide.md
  - Mechanics:
      - Action Replay Codes: mechanics/action_replay_codes.md
      - Important Trainer Rosters: mechanics/important_trainer_rosters.md
      - Item & Trade Changes: mechanics/item_&_trade_changes.md
      - Level Up Move Changes: mechanics/level_up_move_changes.md
      - Pokémon Changes: mechanics/pokemon_changes.md
      - Trainer Rosters: mechanics/trainer_rosters.md
      - Wild Pokémon: mechanics/wild_pokemon.md
  - Pokémon:
      - Placeholder: pokemon/victini.md
  - Routes:
      - Placeholder: pokemon/victini.md
